//
//  AppSupportRegistry.swift
//  PlayTools
//

class AppSupportRegistry {
    static var lookup: [String: AppSupport.Type] = [
        "com.proximabeta.nikke": NIKKESupport.self,
        "com.gamamobi.nikke": NIKKESupport.self,
        "com.tencent.nikke": NIKKESupport.self,
        "com.papegames.infinitynikki": InfinityNikkiSupport.self,
        "com.infoldgames.infinitynikkien": InfinityNikkiSupport.self,
        "com.infoldgames.infinitynikkias": InfinityNikkiSupport.self,
        "com.tencent.jkchess": JinChanChanSupport.self,
        "com.Nekootan.kfkj.apple": OverFieldSupport.self,
        "com.Nekootan.kfkjos.apple": OverFieldSupport.self,
        "com.netease.party": EggyPartySupport.self,
        "com.netease.partyglobal": EggyPartySupport.self,
        "com.netease.eggypartyen": EggyPartySupport.self,
        "com.netease.eggypartyhmt": EggyPartySupport.self,
        "com.epicgames.FortniteGame": FortniteSupport.self,
        "com.tencent.wuxia": MoonlightBladeSupport.self,
        "com.garena.game.mbmtw": MoonlightBladeSupport.self,
        "com.netease.id5": IdentityVSupport.self,
        "com.netease.idv": IdentityVSupport.self,
        "com.netease.idvtw": IdentityVSupport.self,
        "com.ProjectMoon.LimbusCompany": LimbusCompanySupport.self,
        "jp.co.bandainamcoent.BNEI0421": GakuenIdolmasterSupport.self,
        "com.papegames.lysk": LoveAndDeepspaceSupport.self,
        "com.papegames.lysk.en": LoveAndDeepspaceSupport.self,
        "com.papegames.lysk.jp": LoveAndDeepspaceSupport.self,
        "com.netease.rc": RacingMasterSupport.self,
        "com.netease.dfjssea": RacingMasterSupport.self,
        "com.netease.dfjsjp": RacingMasterSupport.self,
        "com.longe.racehmt": RacingMasterSupport.self,
        "com.netease.g108": DestinyRisingSupport.self,
        "com.netease.g108na": DestinyRisingSupport.self,
        "com.netease.g108hmt": DestinyRisingSupport.self,
        "com.netease.g138": UnVEILTheWorldSupport.self,
        "com.netease.g138na": UnVEILTheWorldSupport.self,
        "jp.konami.pesactionmobile": EFootballSupport.self,
        "com.netease.pes": EFootballSupport.self,
        "com.s3.sgzzlb.cn": ThreeKingdomsTacticsSupport.self,
        "com.qookkagame.sgzzlb.jp": ThreeKingdomsTacticsSupport.self,
        "com.qookkagame.sgzzlb.sea": ThreeKingdomsTacticsSupport.self,
        "com.qookkagame.sgzzlb.hkmo": ThreeKingdomsTacticsSupport.self,
        "com.sialiagames.sgzzlb.ios.tw": ThreeKingdomsTacticsSupport.self,
        "com.bilibili.azurlane": AzurLaneSupport.self,
        "com.YoStarJP.AzurLane": AzurLaneSupport.self,
        "com.YoStarEN.AzurLane": AzurLaneSupport.self,
        "com.hkmanjuu.azurlane.ios1": AzurLaneSupport.self,
        "com.netmarble.nanatsunotaizai": SevenDeadlySinsSuport.self,
        "com.netmarble.nanagb": SevenDeadlySinsSuport.self,
        "com.netmarble.nanakr": SevenDeadlySinsSuport.self,
        "com.RoamingStar.StellaSora": StellaSoraSupport.self,
        "com.Stargazer.StellaSora": StellaSoraSupport.self,
        "com.YoStarJP.StellaSora": StellaSoraSupport.self,
        "com.YoStarKR.StellaSora": StellaSoraSupport.self,
        "com.YoStarEN.StellaSora": StellaSoraSupport.self,
        "com.kiif.huijin": EmbersSupport.self,
        "com.dimcroon.hh": RingOfFireSupport.self
    ]
}
